/*
 * This Scala Testsuite was generated by the Gradle 'init' task.
 */
package irld.y1970

import irld.App
import irld.y1970.GeoParser1970.SubRgx
import org.junit.runner.RunWith
import org.scalatest.funsuite.AnyFunSuite
import org.scalatestplus.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class AppSuite extends AnyFunSuite {
  test("App has a greeting") {
    assert(App.greeting() != null)
  }
  test("Record contains .decimal") {
    assert(SubRgx.matches("B137.20"))
  }
}
